### ISSUE TITLE
TMP file, not renamed

### ISSUE THREAD

**Issue by shackrock** [ninthwalker/directPlexDownloader#2]
Similar to the other issue post, the file seems to create a placeholder of proper size (.TMP) - while the progress bar proceeds.  When the progress bar hits 100%, the TMP file remains and there is no renaming that occurrs, powershell remains open showing 100% complete.  By renaming manually to .mkv, the file can be played without any issue.  May be a bug in the script?

**Comment by shackrock** [comment]
Additionally, sometimes the visual download bar does not show, and instead it just says "download completed in 10 seconds" (10 could be any number here).  However, even though this happened and powershell closes after any key is pressed, the download actually does start.  The TMP file is created, and you can see the data transfer via task manager (wifi or ethernet using internet connection).  After that ends, again the file can be renamed manually and it works without issue.  It seems it never enters the while loop for some reason?

**Comment by ninthwalker** [comment]
I’ll have to look into it. Thanks for explaining what’s happening. Something in the Plex code may have changed within the last couple of updates and I’ll need to adjust for that.

**Comment by shackrock** [comment]
A bit more that may help, when I open in ISE instead of just powershell, I did get an error this time and it's still downloading like before to a TMP file. (masked some platform specific stuff):
```

Enter in the Movie or TV Show Metadata ID (ie: 374348): XXXXX
Download Completed in: 10 Seconds
Press any key to exit...Exception calling "ReadKey" with "1" argument(s): "The method or operation is not implemented."
At XXXXXX\directPlexDownloader.ps1:76 char:1
+ $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotImplementedException
```

**Comment by shackrock** [comment]
Any luck? I tried a few things but have not been successful.

**Comment by ninthwalker** [comment]
I've had a brief look, and it seems like something in recent plex server code has changed.
I'll have to find time to dig into it more in the next couple of weeks.

**Comment by shackrock** [comment]
Just an update, doesn't work anymore at all it seems, freezes after entering the ID number - no TMP file created either.  Also can no longer see tokens via browser console, it shows up redacted.

**Comment by kramzero21** [comment]
Just wanted to say that this is a great script and to thank ninthwalker for creating it.

I was able to fix this script, the Bits Job wasn't completing because the command 
Get-BitsTransfer | Complete-BitsTransfer wasn't executed.  Uploaded the script to the following location:

https://github.com/kramzero21/FixeddirectPlexDownloader/tree/master

**Comment by ninthwalker** [comment]
This script/repo is no longer maintained. Please see the new and improved plex downloader app called Saverr.
Thanks!
